/* Automatically @generated by tree-sitter v0.25.10 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 67
#define LARGE_STATE_COUNT 4
#define SYMBOL_COUNT 62
#define ALIAS_COUNT 0
#define TOKEN_COUNT 42
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 3
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define MAX_RESERVED_WORD_SET_SIZE 3
#define PRODUCTION_ID_COUNT 3
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_identifier = 1,
  anon_sym_var = 2,
  anon_sym_EQ = 3,
  anon_sym_const = 4,
  anon_sym_type = 5,
  anon_sym_i8 = 6,
  anon_sym_i16 = 7,
  anon_sym_i32 = 8,
  anon_sym_int = 9,
  anon_sym_i64 = 10,
  anon_sym_u8 = 11,
  anon_sym_u16 = 12,
  anon_sym_u32 = 13,
  anon_sym_uint = 14,
  anon_sym_u64 = 15,
  anon_sym_f32 = 16,
  anon_sym_f64 = 17,
  anon_sym_float = 18,
  anon_sym_bool = 19,
  anon_sym_any = 20,
  anon_sym_string = 21,
  anon_sym_ptr = 22,
  anon_sym_anyptr = 23,
  anon_sym_rawptr = 24,
  anon_sym_self = 25,
  anon_sym_QMARK = 26,
  anon_sym_PIPE = 27,
  sym_intLiteral = 28,
  aux_sym_floatLiteral_token1 = 29,
  aux_sym_floatLiteral_token2 = 30,
  aux_sym_floatLiteral_token3 = 31,
  sym_boolLiteral = 32,
  anon_sym_DQUOTE = 33,
  aux_sym_stringLiteral_token1 = 34,
  anon_sym_BQUOTE = 35,
  anon_sym_SQUOTE = 36,
  aux_sym_charLiteral_token1 = 37,
  anon_sym_LBRACK = 38,
  anon_sym_COMMA = 39,
  anon_sym_RBRACK = 40,
  anon_sym_null = 41,
  sym_source_file = 42,
  sym_statements = 43,
  sym_varDecl = 44,
  sym_constDecl = 45,
  sym_typeDecl = 46,
  sym_expression = 47,
  sym_type = 48,
  sym_baseType = 49,
  sym_singleType = 50,
  sym_optionType = 51,
  sym_unionType = 52,
  sym_numberLiteral = 53,
  sym_floatLiteral = 54,
  sym_stringLiteral = 55,
  sym_charLiteral = 56,
  sym_arrayLiteral = 57,
  sym__null = 58,
  aux_sym_source_file_repeat1 = 59,
  aux_sym_unionType_repeat1 = 60,
  aux_sym_arrayLiteral_repeat1 = 61,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [anon_sym_var] = "var",
  [anon_sym_EQ] = "=",
  [anon_sym_const] = "const",
  [anon_sym_type] = "type",
  [anon_sym_i8] = "i8",
  [anon_sym_i16] = "i16",
  [anon_sym_i32] = "i32",
  [anon_sym_int] = "int",
  [anon_sym_i64] = "i64",
  [anon_sym_u8] = "u8",
  [anon_sym_u16] = "u16",
  [anon_sym_u32] = "u32",
  [anon_sym_uint] = "uint",
  [anon_sym_u64] = "u64",
  [anon_sym_f32] = "f32",
  [anon_sym_f64] = "f64",
  [anon_sym_float] = "float",
  [anon_sym_bool] = "bool",
  [anon_sym_any] = "any",
  [anon_sym_string] = "string",
  [anon_sym_ptr] = "ptr",
  [anon_sym_anyptr] = "anyptr",
  [anon_sym_rawptr] = "rawptr",
  [anon_sym_self] = "self",
  [anon_sym_QMARK] = "\?",
  [anon_sym_PIPE] = "|",
  [sym_intLiteral] = "intLiteral",
  [aux_sym_floatLiteral_token1] = "floatLiteral_token1",
  [aux_sym_floatLiteral_token2] = "floatLiteral_token2",
  [aux_sym_floatLiteral_token3] = "floatLiteral_token3",
  [sym_boolLiteral] = "boolLiteral",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_stringLiteral_token1] = "stringLiteral_token1",
  [anon_sym_BQUOTE] = "`",
  [anon_sym_SQUOTE] = "'",
  [aux_sym_charLiteral_token1] = "charLiteral_token1",
  [anon_sym_LBRACK] = "[",
  [anon_sym_COMMA] = ",",
  [anon_sym_RBRACK] = "]",
  [anon_sym_null] = "null",
  [sym_source_file] = "source_file",
  [sym_statements] = "statements",
  [sym_varDecl] = "varDecl",
  [sym_constDecl] = "constDecl",
  [sym_typeDecl] = "typeDecl",
  [sym_expression] = "expression",
  [sym_type] = "type",
  [sym_baseType] = "baseType",
  [sym_singleType] = "singleType",
  [sym_optionType] = "optionType",
  [sym_unionType] = "unionType",
  [sym_numberLiteral] = "numberLiteral",
  [sym_floatLiteral] = "floatLiteral",
  [sym_stringLiteral] = "stringLiteral",
  [sym_charLiteral] = "charLiteral",
  [sym_arrayLiteral] = "arrayLiteral",
  [sym__null] = "_null",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_unionType_repeat1] = "unionType_repeat1",
  [aux_sym_arrayLiteral_repeat1] = "arrayLiteral_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [anon_sym_var] = anon_sym_var,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_const] = anon_sym_const,
  [anon_sym_type] = anon_sym_type,
  [anon_sym_i8] = anon_sym_i8,
  [anon_sym_i16] = anon_sym_i16,
  [anon_sym_i32] = anon_sym_i32,
  [anon_sym_int] = anon_sym_int,
  [anon_sym_i64] = anon_sym_i64,
  [anon_sym_u8] = anon_sym_u8,
  [anon_sym_u16] = anon_sym_u16,
  [anon_sym_u32] = anon_sym_u32,
  [anon_sym_uint] = anon_sym_uint,
  [anon_sym_u64] = anon_sym_u64,
  [anon_sym_f32] = anon_sym_f32,
  [anon_sym_f64] = anon_sym_f64,
  [anon_sym_float] = anon_sym_float,
  [anon_sym_bool] = anon_sym_bool,
  [anon_sym_any] = anon_sym_any,
  [anon_sym_string] = anon_sym_string,
  [anon_sym_ptr] = anon_sym_ptr,
  [anon_sym_anyptr] = anon_sym_anyptr,
  [anon_sym_rawptr] = anon_sym_rawptr,
  [anon_sym_self] = anon_sym_self,
  [anon_sym_QMARK] = anon_sym_QMARK,
  [anon_sym_PIPE] = anon_sym_PIPE,
  [sym_intLiteral] = sym_intLiteral,
  [aux_sym_floatLiteral_token1] = aux_sym_floatLiteral_token1,
  [aux_sym_floatLiteral_token2] = aux_sym_floatLiteral_token2,
  [aux_sym_floatLiteral_token3] = aux_sym_floatLiteral_token3,
  [sym_boolLiteral] = sym_boolLiteral,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_stringLiteral_token1] = aux_sym_stringLiteral_token1,
  [anon_sym_BQUOTE] = anon_sym_BQUOTE,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [aux_sym_charLiteral_token1] = aux_sym_charLiteral_token1,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_null] = anon_sym_null,
  [sym_source_file] = sym_source_file,
  [sym_statements] = sym_statements,
  [sym_varDecl] = sym_varDecl,
  [sym_constDecl] = sym_constDecl,
  [sym_typeDecl] = sym_typeDecl,
  [sym_expression] = sym_expression,
  [sym_type] = sym_type,
  [sym_baseType] = sym_baseType,
  [sym_singleType] = sym_singleType,
  [sym_optionType] = sym_optionType,
  [sym_unionType] = sym_unionType,
  [sym_numberLiteral] = sym_numberLiteral,
  [sym_floatLiteral] = sym_floatLiteral,
  [sym_stringLiteral] = sym_stringLiteral,
  [sym_charLiteral] = sym_charLiteral,
  [sym_arrayLiteral] = sym_arrayLiteral,
  [sym__null] = sym__null,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_unionType_repeat1] = aux_sym_unionType_repeat1,
  [aux_sym_arrayLiteral_repeat1] = aux_sym_arrayLiteral_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_var] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_const] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_type] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_i8] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_i16] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_i32] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_int] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_i64] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_u8] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_u16] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_u32] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_uint] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_u64] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_f32] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_f64] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_float] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_bool] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_any] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_string] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ptr] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_anyptr] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_rawptr] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_self] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_QMARK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE] = {
    .visible = true,
    .named = false,
  },
  [sym_intLiteral] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_floatLiteral_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_floatLiteral_token2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_floatLiteral_token3] = {
    .visible = false,
    .named = false,
  },
  [sym_boolLiteral] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_stringLiteral_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_BQUOTE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_charLiteral_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_null] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_statements] = {
    .visible = true,
    .named = true,
  },
  [sym_varDecl] = {
    .visible = true,
    .named = true,
  },
  [sym_constDecl] = {
    .visible = true,
    .named = true,
  },
  [sym_typeDecl] = {
    .visible = true,
    .named = true,
  },
  [sym_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_type] = {
    .visible = true,
    .named = true,
  },
  [sym_baseType] = {
    .visible = true,
    .named = true,
  },
  [sym_singleType] = {
    .visible = true,
    .named = true,
  },
  [sym_optionType] = {
    .visible = true,
    .named = true,
  },
  [sym_unionType] = {
    .visible = true,
    .named = true,
  },
  [sym_numberLiteral] = {
    .visible = true,
    .named = true,
  },
  [sym_floatLiteral] = {
    .visible = true,
    .named = true,
  },
  [sym_stringLiteral] = {
    .visible = true,
    .named = true,
  },
  [sym_charLiteral] = {
    .visible = true,
    .named = true,
  },
  [sym_arrayLiteral] = {
    .visible = true,
    .named = true,
  },
  [sym__null] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_unionType_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_arrayLiteral_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_name = 1,
  field_type_name = 2,
  field_type_value = 3,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_name] = "name",
  [field_type_name] = "type_name",
  [field_type_value] = "type_value",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 1},
  [1] =
    {field_type_name, 1},
    {field_type_value, 3},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 14,
  [25] = 25,
  [26] = 26,
  [27] = 25,
  [28] = 28,
  [29] = 28,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 22,
  [34] = 17,
  [35] = 13,
  [36] = 15,
  [37] = 21,
  [38] = 20,
  [39] = 39,
  [40] = 6,
  [41] = 8,
  [42] = 7,
  [43] = 9,
  [44] = 5,
  [45] = 11,
  [46] = 10,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 23,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 47,
  [59] = 48,
  [60] = 57,
  [61] = 61,
  [62] = 62,
  [63] = 62,
  [64] = 53,
  [65] = 54,
  [66] = 66,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(8);
      ADVANCE_MAP(
        '"', 21,
        '\'', 24,
        ',', 29,
        '.', 4,
        '0', 12,
        '=', 9,
        '?', 10,
        '[', 28,
        ']', 30,
        '`', 23,
        '|', 11,
        'E', 26,
        'e', 26,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(13);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('_' <= lookahead && lookahead <= 'z')) ADVANCE(27);
      END_STATE();
    case 1:
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(19);
      END_STATE();
    case 2:
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(20);
      END_STATE();
    case 3:
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(18);
      END_STATE();
    case 4:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(2);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(4);
      END_STATE();
    case 5:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(5);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(22);
      END_STATE();
    case 6:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(6);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(25);
      END_STATE();
    case 7:
      if (eof) ADVANCE(8);
      ADVANCE_MAP(
        '"', 21,
        '\'', 24,
        ',', 29,
        '.', 4,
        '0', 12,
        '?', 10,
        '[', 28,
        ']', 30,
        '`', 23,
        '|', 11,
        'E', 31,
        'e', 31,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(7);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(13);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('_' <= lookahead && lookahead <= 'z')) ADVANCE(32);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_QMARK);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_PIPE);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(sym_intLiteral);
      if (lookahead == '.') ADVANCE(17);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(1);
      if (lookahead == 'X' ||
          lookahead == 'x') ADVANCE(16);
      if (lookahead == '8' ||
          lookahead == '9') ADVANCE(15);
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(14);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(sym_intLiteral);
      if (lookahead == '.') ADVANCE(17);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(15);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(sym_intLiteral);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(1);
      if (lookahead == '8' ||
          lookahead == '9') ADVANCE(15);
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(14);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym_intLiteral);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(15);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_intLiteral);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(16);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(aux_sym_floatLiteral_token1);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(3);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(17);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(aux_sym_floatLiteral_token1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(18);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(aux_sym_floatLiteral_token2);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(19);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(aux_sym_floatLiteral_token3);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(20);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(aux_sym_stringLiteral_token1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(22);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_BQUOTE);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(aux_sym_charLiteral_token1);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(aux_sym_charLiteral_token1);
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(19);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(32);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(aux_sym_charLiteral_token1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(32);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(19);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(32);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(32);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      ADVANCE_MAP(
        'a', 1,
        'b', 2,
        'c', 3,
        'f', 4,
        'i', 5,
        'n', 6,
        'p', 7,
        'r', 8,
        's', 9,
        't', 10,
        'u', 11,
        'v', 12,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == 'n') ADVANCE(13);
      END_STATE();
    case 2:
      if (lookahead == 'o') ADVANCE(14);
      END_STATE();
    case 3:
      if (lookahead == 'o') ADVANCE(15);
      END_STATE();
    case 4:
      if (lookahead == '3') ADVANCE(16);
      if (lookahead == '6') ADVANCE(17);
      if (lookahead == 'a') ADVANCE(18);
      if (lookahead == 'l') ADVANCE(19);
      END_STATE();
    case 5:
      if (lookahead == '1') ADVANCE(20);
      if (lookahead == '3') ADVANCE(21);
      if (lookahead == '6') ADVANCE(22);
      if (lookahead == '8') ADVANCE(23);
      if (lookahead == 'n') ADVANCE(24);
      END_STATE();
    case 6:
      if (lookahead == 'u') ADVANCE(25);
      END_STATE();
    case 7:
      if (lookahead == 't') ADVANCE(26);
      END_STATE();
    case 8:
      if (lookahead == 'a') ADVANCE(27);
      END_STATE();
    case 9:
      if (lookahead == 'e') ADVANCE(28);
      if (lookahead == 't') ADVANCE(29);
      END_STATE();
    case 10:
      if (lookahead == 'r') ADVANCE(30);
      if (lookahead == 'y') ADVANCE(31);
      END_STATE();
    case 11:
      if (lookahead == '1') ADVANCE(32);
      if (lookahead == '3') ADVANCE(33);
      if (lookahead == '6') ADVANCE(34);
      if (lookahead == '8') ADVANCE(35);
      if (lookahead == 'i') ADVANCE(36);
      END_STATE();
    case 12:
      if (lookahead == 'a') ADVANCE(37);
      END_STATE();
    case 13:
      if (lookahead == 'y') ADVANCE(38);
      END_STATE();
    case 14:
      if (lookahead == 'o') ADVANCE(39);
      END_STATE();
    case 15:
      if (lookahead == 'n') ADVANCE(40);
      END_STATE();
    case 16:
      if (lookahead == '2') ADVANCE(41);
      END_STATE();
    case 17:
      if (lookahead == '4') ADVANCE(42);
      END_STATE();
    case 18:
      if (lookahead == 'l') ADVANCE(43);
      END_STATE();
    case 19:
      if (lookahead == 'o') ADVANCE(44);
      END_STATE();
    case 20:
      if (lookahead == '6') ADVANCE(45);
      END_STATE();
    case 21:
      if (lookahead == '2') ADVANCE(46);
      END_STATE();
    case 22:
      if (lookahead == '4') ADVANCE(47);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_i8);
      END_STATE();
    case 24:
      if (lookahead == 't') ADVANCE(48);
      END_STATE();
    case 25:
      if (lookahead == 'l') ADVANCE(49);
      END_STATE();
    case 26:
      if (lookahead == 'r') ADVANCE(50);
      END_STATE();
    case 27:
      if (lookahead == 'w') ADVANCE(51);
      END_STATE();
    case 28:
      if (lookahead == 'l') ADVANCE(52);
      END_STATE();
    case 29:
      if (lookahead == 'r') ADVANCE(53);
      END_STATE();
    case 30:
      if (lookahead == 'u') ADVANCE(54);
      END_STATE();
    case 31:
      if (lookahead == 'p') ADVANCE(55);
      END_STATE();
    case 32:
      if (lookahead == '6') ADVANCE(56);
      END_STATE();
    case 33:
      if (lookahead == '2') ADVANCE(57);
      END_STATE();
    case 34:
      if (lookahead == '4') ADVANCE(58);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_u8);
      END_STATE();
    case 36:
      if (lookahead == 'n') ADVANCE(59);
      END_STATE();
    case 37:
      if (lookahead == 'r') ADVANCE(60);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_any);
      if (lookahead == 'p') ADVANCE(61);
      END_STATE();
    case 39:
      if (lookahead == 'l') ADVANCE(62);
      END_STATE();
    case 40:
      if (lookahead == 's') ADVANCE(63);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_f32);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_f64);
      END_STATE();
    case 43:
      if (lookahead == 's') ADVANCE(64);
      END_STATE();
    case 44:
      if (lookahead == 'a') ADVANCE(65);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_i16);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_i32);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_i64);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_int);
      END_STATE();
    case 49:
      if (lookahead == 'l') ADVANCE(66);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_ptr);
      END_STATE();
    case 51:
      if (lookahead == 'p') ADVANCE(67);
      END_STATE();
    case 52:
      if (lookahead == 'f') ADVANCE(68);
      END_STATE();
    case 53:
      if (lookahead == 'i') ADVANCE(69);
      END_STATE();
    case 54:
      if (lookahead == 'e') ADVANCE(70);
      END_STATE();
    case 55:
      if (lookahead == 'e') ADVANCE(71);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_u16);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(anon_sym_u32);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(anon_sym_u64);
      END_STATE();
    case 59:
      if (lookahead == 't') ADVANCE(72);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(anon_sym_var);
      END_STATE();
    case 61:
      if (lookahead == 't') ADVANCE(73);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(anon_sym_bool);
      END_STATE();
    case 63:
      if (lookahead == 't') ADVANCE(74);
      END_STATE();
    case 64:
      if (lookahead == 'e') ADVANCE(70);
      END_STATE();
    case 65:
      if (lookahead == 't') ADVANCE(75);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(anon_sym_null);
      END_STATE();
    case 67:
      if (lookahead == 't') ADVANCE(76);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(anon_sym_self);
      END_STATE();
    case 69:
      if (lookahead == 'n') ADVANCE(77);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(sym_boolLiteral);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(anon_sym_type);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(anon_sym_uint);
      END_STATE();
    case 73:
      if (lookahead == 'r') ADVANCE(78);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(anon_sym_const);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(anon_sym_float);
      END_STATE();
    case 76:
      if (lookahead == 'r') ADVANCE(79);
      END_STATE();
    case 77:
      if (lookahead == 'g') ADVANCE(80);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(anon_sym_anyptr);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(anon_sym_rawptr);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(anon_sym_string);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 7},
  [2] = {.lex_state = 7},
  [3] = {.lex_state = 7},
  [4] = {.lex_state = 7},
  [5] = {.lex_state = 7},
  [6] = {.lex_state = 7},
  [7] = {.lex_state = 7},
  [8] = {.lex_state = 7},
  [9] = {.lex_state = 7},
  [10] = {.lex_state = 7},
  [11] = {.lex_state = 7},
  [12] = {.lex_state = 7},
  [13] = {.lex_state = 7},
  [14] = {.lex_state = 7},
  [15] = {.lex_state = 7},
  [16] = {.lex_state = 7},
  [17] = {.lex_state = 7},
  [18] = {.lex_state = 7},
  [19] = {.lex_state = 7},
  [20] = {.lex_state = 7},
  [21] = {.lex_state = 7},
  [22] = {.lex_state = 7},
  [23] = {.lex_state = 7},
  [24] = {.lex_state = 7},
  [25] = {.lex_state = 7, .reserved_word_set_id = 1},
  [26] = {.lex_state = 7, .reserved_word_set_id = 1},
  [27] = {.lex_state = 7, .reserved_word_set_id = 1},
  [28] = {.lex_state = 7, .reserved_word_set_id = 1},
  [29] = {.lex_state = 7, .reserved_word_set_id = 1},
  [30] = {.lex_state = 7, .reserved_word_set_id = 1},
  [31] = {.lex_state = 7, .reserved_word_set_id = 1},
  [32] = {.lex_state = 7, .reserved_word_set_id = 1},
  [33] = {.lex_state = 7, .reserved_word_set_id = 1},
  [34] = {.lex_state = 7, .reserved_word_set_id = 1},
  [35] = {.lex_state = 7, .reserved_word_set_id = 1},
  [36] = {.lex_state = 7, .reserved_word_set_id = 1},
  [37] = {.lex_state = 7, .reserved_word_set_id = 1},
  [38] = {.lex_state = 7, .reserved_word_set_id = 1},
  [39] = {.lex_state = 7, .reserved_word_set_id = 1},
  [40] = {.lex_state = 7, .reserved_word_set_id = 1},
  [41] = {.lex_state = 7, .reserved_word_set_id = 1},
  [42] = {.lex_state = 7, .reserved_word_set_id = 1},
  [43] = {.lex_state = 7, .reserved_word_set_id = 1},
  [44] = {.lex_state = 7, .reserved_word_set_id = 1},
  [45] = {.lex_state = 7, .reserved_word_set_id = 1},
  [46] = {.lex_state = 7, .reserved_word_set_id = 1},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 7, .reserved_word_set_id = 1},
  [51] = {.lex_state = 7, .reserved_word_set_id = 1},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 5},
  [54] = {.lex_state = 6},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 7, .reserved_word_set_id = 1},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 5},
  [63] = {.lex_state = 5},
  [64] = {.lex_state = 5},
  [65] = {.lex_state = 6},
  [66] = {.lex_state = 7, .reserved_word_set_id = 1},
};

static const TSSymbol ts_reserved_words[2][MAX_RESERVED_WORD_SET_SIZE] = {
  [1] = {
    anon_sym_var,
    anon_sym_const,
    anon_sym_type,
  },
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_var] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_const] = ACTIONS(1),
    [anon_sym_type] = ACTIONS(1),
    [anon_sym_i8] = ACTIONS(1),
    [anon_sym_i16] = ACTIONS(1),
    [anon_sym_i32] = ACTIONS(1),
    [anon_sym_int] = ACTIONS(1),
    [anon_sym_i64] = ACTIONS(1),
    [anon_sym_u8] = ACTIONS(1),
    [anon_sym_u16] = ACTIONS(1),
    [anon_sym_u32] = ACTIONS(1),
    [anon_sym_uint] = ACTIONS(1),
    [anon_sym_u64] = ACTIONS(1),
    [anon_sym_f32] = ACTIONS(1),
    [anon_sym_f64] = ACTIONS(1),
    [anon_sym_float] = ACTIONS(1),
    [anon_sym_bool] = ACTIONS(1),
    [anon_sym_any] = ACTIONS(1),
    [anon_sym_string] = ACTIONS(1),
    [anon_sym_ptr] = ACTIONS(1),
    [anon_sym_anyptr] = ACTIONS(1),
    [anon_sym_rawptr] = ACTIONS(1),
    [anon_sym_self] = ACTIONS(1),
    [anon_sym_QMARK] = ACTIONS(1),
    [anon_sym_PIPE] = ACTIONS(1),
    [sym_intLiteral] = ACTIONS(1),
    [aux_sym_floatLiteral_token1] = ACTIONS(1),
    [aux_sym_floatLiteral_token2] = ACTIONS(1),
    [aux_sym_floatLiteral_token3] = ACTIONS(1),
    [sym_boolLiteral] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_BQUOTE] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [aux_sym_charLiteral_token1] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_null] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(55),
    [sym_statements] = STATE(2),
    [sym_varDecl] = STATE(12),
    [sym_constDecl] = STATE(12),
    [sym_typeDecl] = STATE(12),
    [sym_type] = STATE(56),
    [sym_baseType] = STATE(40),
    [sym_singleType] = STATE(42),
    [sym_optionType] = STATE(42),
    [sym_unionType] = STATE(50),
    [sym__null] = STATE(44),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_var] = ACTIONS(5),
    [anon_sym_const] = ACTIONS(7),
    [anon_sym_type] = ACTIONS(9),
    [anon_sym_i8] = ACTIONS(11),
    [anon_sym_i16] = ACTIONS(11),
    [anon_sym_i32] = ACTIONS(11),
    [anon_sym_int] = ACTIONS(11),
    [anon_sym_i64] = ACTIONS(11),
    [anon_sym_u8] = ACTIONS(11),
    [anon_sym_u16] = ACTIONS(11),
    [anon_sym_u32] = ACTIONS(11),
    [anon_sym_uint] = ACTIONS(11),
    [anon_sym_u64] = ACTIONS(11),
    [anon_sym_f32] = ACTIONS(11),
    [anon_sym_f64] = ACTIONS(11),
    [anon_sym_float] = ACTIONS(11),
    [anon_sym_bool] = ACTIONS(11),
    [anon_sym_any] = ACTIONS(13),
    [anon_sym_string] = ACTIONS(11),
    [anon_sym_ptr] = ACTIONS(11),
    [anon_sym_anyptr] = ACTIONS(11),
    [anon_sym_rawptr] = ACTIONS(11),
    [anon_sym_self] = ACTIONS(11),
    [anon_sym_null] = ACTIONS(11),
  },
  [STATE(2)] = {
    [sym_statements] = STATE(3),
    [sym_varDecl] = STATE(12),
    [sym_constDecl] = STATE(12),
    [sym_typeDecl] = STATE(12),
    [sym_type] = STATE(56),
    [sym_baseType] = STATE(40),
    [sym_singleType] = STATE(42),
    [sym_optionType] = STATE(42),
    [sym_unionType] = STATE(50),
    [sym__null] = STATE(44),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(15),
    [anon_sym_var] = ACTIONS(5),
    [anon_sym_const] = ACTIONS(7),
    [anon_sym_type] = ACTIONS(9),
    [anon_sym_i8] = ACTIONS(11),
    [anon_sym_i16] = ACTIONS(11),
    [anon_sym_i32] = ACTIONS(11),
    [anon_sym_int] = ACTIONS(11),
    [anon_sym_i64] = ACTIONS(11),
    [anon_sym_u8] = ACTIONS(11),
    [anon_sym_u16] = ACTIONS(11),
    [anon_sym_u32] = ACTIONS(11),
    [anon_sym_uint] = ACTIONS(11),
    [anon_sym_u64] = ACTIONS(11),
    [anon_sym_f32] = ACTIONS(11),
    [anon_sym_f64] = ACTIONS(11),
    [anon_sym_float] = ACTIONS(11),
    [anon_sym_bool] = ACTIONS(11),
    [anon_sym_any] = ACTIONS(13),
    [anon_sym_string] = ACTIONS(11),
    [anon_sym_ptr] = ACTIONS(11),
    [anon_sym_anyptr] = ACTIONS(11),
    [anon_sym_rawptr] = ACTIONS(11),
    [anon_sym_self] = ACTIONS(11),
    [anon_sym_null] = ACTIONS(11),
  },
  [STATE(3)] = {
    [sym_statements] = STATE(3),
    [sym_varDecl] = STATE(12),
    [sym_constDecl] = STATE(12),
    [sym_typeDecl] = STATE(12),
    [sym_type] = STATE(56),
    [sym_baseType] = STATE(40),
    [sym_singleType] = STATE(42),
    [sym_optionType] = STATE(42),
    [sym_unionType] = STATE(50),
    [sym__null] = STATE(44),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(17),
    [anon_sym_var] = ACTIONS(19),
    [anon_sym_const] = ACTIONS(22),
    [anon_sym_type] = ACTIONS(25),
    [anon_sym_i8] = ACTIONS(28),
    [anon_sym_i16] = ACTIONS(28),
    [anon_sym_i32] = ACTIONS(28),
    [anon_sym_int] = ACTIONS(28),
    [anon_sym_i64] = ACTIONS(28),
    [anon_sym_u8] = ACTIONS(28),
    [anon_sym_u16] = ACTIONS(28),
    [anon_sym_u32] = ACTIONS(28),
    [anon_sym_uint] = ACTIONS(28),
    [anon_sym_u64] = ACTIONS(28),
    [anon_sym_f32] = ACTIONS(28),
    [anon_sym_f64] = ACTIONS(28),
    [anon_sym_float] = ACTIONS(28),
    [anon_sym_bool] = ACTIONS(28),
    [anon_sym_any] = ACTIONS(31),
    [anon_sym_string] = ACTIONS(28),
    [anon_sym_ptr] = ACTIONS(28),
    [anon_sym_anyptr] = ACTIONS(28),
    [anon_sym_rawptr] = ACTIONS(28),
    [anon_sym_self] = ACTIONS(28),
    [anon_sym_null] = ACTIONS(28),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 7,
    ACTIONS(36), 1,
      anon_sym_any,
    STATE(5), 1,
      sym__null,
    STATE(6), 1,
      sym_baseType,
    STATE(19), 1,
      sym_type,
    STATE(23), 1,
      sym_unionType,
    STATE(7), 2,
      sym_singleType,
      sym_optionType,
    ACTIONS(34), 20,
      anon_sym_i8,
      anon_sym_i16,
      anon_sym_i32,
      anon_sym_int,
      anon_sym_i64,
      anon_sym_u8,
      anon_sym_u16,
      anon_sym_u32,
      anon_sym_uint,
      anon_sym_u64,
      anon_sym_f32,
      anon_sym_f64,
      anon_sym_float,
      anon_sym_bool,
      anon_sym_string,
      anon_sym_ptr,
      anon_sym_anyptr,
      anon_sym_rawptr,
      anon_sym_self,
      anon_sym_null,
  [42] = 2,
    ACTIONS(40), 1,
      anon_sym_any,
    ACTIONS(38), 26,
      ts_builtin_sym_end,
      anon_sym_var,
      anon_sym_const,
      anon_sym_type,
      anon_sym_i8,
      anon_sym_i16,
      anon_sym_i32,
      anon_sym_int,
      anon_sym_i64,
      anon_sym_u8,
      anon_sym_u16,
      anon_sym_u32,
      anon_sym_uint,
      anon_sym_u64,
      anon_sym_f32,
      anon_sym_f64,
      anon_sym_float,
      anon_sym_bool,
      anon_sym_string,
      anon_sym_ptr,
      anon_sym_anyptr,
      anon_sym_rawptr,
      anon_sym_self,
      anon_sym_QMARK,
      anon_sym_PIPE,
      anon_sym_null,
  [74] = 3,
    ACTIONS(44), 1,
      anon_sym_any,
    ACTIONS(46), 1,
      anon_sym_QMARK,
    ACTIONS(42), 25,
      ts_builtin_sym_end,
      anon_sym_var,
      anon_sym_const,
      anon_sym_type,
      anon_sym_i8,
      anon_sym_i16,
      anon_sym_i32,
      anon_sym_int,
      anon_sym_i64,
      anon_sym_u8,
      anon_sym_u16,
      anon_sym_u32,
      anon_sym_uint,
      anon_sym_u64,
      anon_sym_f32,
      anon_sym_f64,
      anon_sym_float,
      anon_sym_bool,
      anon_sym_string,
      anon_sym_ptr,
      anon_sym_anyptr,
      anon_sym_rawptr,
      anon_sym_self,
      anon_sym_PIPE,
      anon_sym_null,
  [108] = 4,
    ACTIONS(50), 1,
      anon_sym_any,
    ACTIONS(52), 1,
      anon_sym_PIPE,
    STATE(8), 1,
      aux_sym_unionType_repeat1,
    ACTIONS(48), 24,
      ts_builtin_sym_end,
      anon_sym_var,
      anon_sym_const,
      anon_sym_type,
      anon_sym_i8,
      anon_sym_i16,
      anon_sym_i32,
      anon_sym_int,
      anon_sym_i64,
      anon_sym_u8,
      anon_sym_u16,
      anon_sym_u32,
      anon_sym_uint,
      anon_sym_u64,
      anon_sym_f32,
      anon_sym_f64,
      anon_sym_float,
      anon_sym_bool,
      anon_sym_string,
      anon_sym_ptr,
      anon_sym_anyptr,
      anon_sym_rawptr,
      anon_sym_self,
      anon_sym_null,
  [144] = 4,
    ACTIONS(52), 1,
      anon_sym_PIPE,
    ACTIONS(56), 1,
      anon_sym_any,
    STATE(9), 1,
      aux_sym_unionType_repeat1,
    ACTIONS(54), 24,
      ts_builtin_sym_end,
      anon_sym_var,
      anon_sym_const,
      anon_sym_type,
      anon_sym_i8,
      anon_sym_i16,
      anon_sym_i32,
      anon_sym_int,
      anon_sym_i64,
      anon_sym_u8,
      anon_sym_u16,
      anon_sym_u32,
      anon_sym_uint,
      anon_sym_u64,
      anon_sym_f32,
      anon_sym_f64,
      anon_sym_float,
      anon_sym_bool,
      anon_sym_string,
      anon_sym_ptr,
      anon_sym_anyptr,
      anon_sym_rawptr,
      anon_sym_self,
      anon_sym_null,
  [180] = 4,
    ACTIONS(60), 1,
      anon_sym_any,
    ACTIONS(62), 1,
      anon_sym_PIPE,
    STATE(9), 1,
      aux_sym_unionType_repeat1,
    ACTIONS(58), 24,
      ts_builtin_sym_end,
      anon_sym_var,
      anon_sym_const,
      anon_sym_type,
      anon_sym_i8,
      anon_sym_i16,
      anon_sym_i32,
      anon_sym_int,
      anon_sym_i64,
      anon_sym_u8,
      anon_sym_u16,
      anon_sym_u32,
      anon_sym_uint,
      anon_sym_u64,
      anon_sym_f32,
      anon_sym_f64,
      anon_sym_float,
      anon_sym_bool,
      anon_sym_string,
      anon_sym_ptr,
      anon_sym_anyptr,
      anon_sym_rawptr,
      anon_sym_self,
      anon_sym_null,
  [216] = 2,
    ACTIONS(67), 1,
      anon_sym_any,
    ACTIONS(65), 25,
      ts_builtin_sym_end,
      anon_sym_var,
      anon_sym_const,
      anon_sym_type,
      anon_sym_i8,
      anon_sym_i16,
      anon_sym_i32,
      anon_sym_int,
      anon_sym_i64,
      anon_sym_u8,
      anon_sym_u16,
      anon_sym_u32,
      anon_sym_uint,
      anon_sym_u64,
      anon_sym_f32,
      anon_sym_f64,
      anon_sym_float,
      anon_sym_bool,
      anon_sym_string,
      anon_sym_ptr,
      anon_sym_anyptr,
      anon_sym_rawptr,
      anon_sym_self,
      anon_sym_PIPE,
      anon_sym_null,
  [247] = 2,
    ACTIONS(60), 1,
      anon_sym_any,
    ACTIONS(58), 25,
      ts_builtin_sym_end,
      anon_sym_var,
      anon_sym_const,
      anon_sym_type,
      anon_sym_i8,
      anon_sym_i16,
      anon_sym_i32,
      anon_sym_int,
      anon_sym_i64,
      anon_sym_u8,
      anon_sym_u16,
      anon_sym_u32,
      anon_sym_uint,
      anon_sym_u64,
      anon_sym_f32,
      anon_sym_f64,
      anon_sym_float,
      anon_sym_bool,
      anon_sym_string,
      anon_sym_ptr,
      anon_sym_anyptr,
      anon_sym_rawptr,
      anon_sym_self,
      anon_sym_PIPE,
      anon_sym_null,
  [278] = 2,
    ACTIONS(71), 1,
      anon_sym_any,
    ACTIONS(69), 24,
      ts_builtin_sym_end,
      anon_sym_var,
      anon_sym_const,
      anon_sym_type,
      anon_sym_i8,
      anon_sym_i16,
      anon_sym_i32,
      anon_sym_int,
      anon_sym_i64,
      anon_sym_u8,
      anon_sym_u16,
      anon_sym_u32,
      anon_sym_uint,
      anon_sym_u64,
      anon_sym_f32,
      anon_sym_f64,
      anon_sym_float,
      anon_sym_bool,
      anon_sym_string,
      anon_sym_ptr,
      anon_sym_anyptr,
      anon_sym_rawptr,
      anon_sym_self,
      anon_sym_null,
  [308] = 2,
    ACTIONS(75), 1,
      anon_sym_any,
    ACTIONS(73), 24,
      ts_builtin_sym_end,
      anon_sym_var,
      anon_sym_const,
      anon_sym_type,
      anon_sym_i8,
      anon_sym_i16,
      anon_sym_i32,
      anon_sym_int,
      anon_sym_i64,
      anon_sym_u8,
      anon_sym_u16,
      anon_sym_u32,
      anon_sym_uint,
      anon_sym_u64,
      anon_sym_f32,
      anon_sym_f64,
      anon_sym_float,
      anon_sym_bool,
      anon_sym_string,
      anon_sym_ptr,
      anon_sym_anyptr,
      anon_sym_rawptr,
      anon_sym_self,
      anon_sym_null,
  [338] = 5,
    ACTIONS(13), 1,
      anon_sym_any,
    STATE(40), 1,
      sym_baseType,
    STATE(44), 1,
      sym__null,
    STATE(45), 2,
      sym_singleType,
      sym_optionType,
    ACTIONS(11), 20,
      anon_sym_i8,
      anon_sym_i16,
      anon_sym_i32,
      anon_sym_int,
      anon_sym_i64,
      anon_sym_u8,
      anon_sym_u16,
      anon_sym_u32,
      anon_sym_uint,
      anon_sym_u64,
      anon_sym_f32,
      anon_sym_f64,
      anon_sym_float,
      anon_sym_bool,
      anon_sym_string,
      anon_sym_ptr,
      anon_sym_anyptr,
      anon_sym_rawptr,
      anon_sym_self,
      anon_sym_null,
  [374] = 2,
    ACTIONS(79), 1,
      anon_sym_any,
    ACTIONS(77), 24,
      ts_builtin_sym_end,
      anon_sym_var,
      anon_sym_const,
      anon_sym_type,
      anon_sym_i8,
      anon_sym_i16,
      anon_sym_i32,
      anon_sym_int,
      anon_sym_i64,
      anon_sym_u8,
      anon_sym_u16,
      anon_sym_u32,
      anon_sym_uint,
      anon_sym_u64,
      anon_sym_f32,
      anon_sym_f64,
      anon_sym_float,
      anon_sym_bool,
      anon_sym_string,
      anon_sym_ptr,
      anon_sym_anyptr,
      anon_sym_rawptr,
      anon_sym_self,
      anon_sym_null,
  [404] = 2,
    ACTIONS(83), 1,
      anon_sym_any,
    ACTIONS(81), 24,
      ts_builtin_sym_end,
      anon_sym_var,
      anon_sym_const,
      anon_sym_type,
      anon_sym_i8,
      anon_sym_i16,
      anon_sym_i32,
      anon_sym_int,
      anon_sym_i64,
      anon_sym_u8,
      anon_sym_u16,
      anon_sym_u32,
      anon_sym_uint,
      anon_sym_u64,
      anon_sym_f32,
      anon_sym_f64,
      anon_sym_float,
      anon_sym_bool,
      anon_sym_string,
      anon_sym_ptr,
      anon_sym_anyptr,
      anon_sym_rawptr,
      anon_sym_self,
      anon_sym_null,
  [434] = 2,
    ACTIONS(87), 1,
      anon_sym_any,
    ACTIONS(85), 24,
      ts_builtin_sym_end,
      anon_sym_var,
      anon_sym_const,
      anon_sym_type,
      anon_sym_i8,
      anon_sym_i16,
      anon_sym_i32,
      anon_sym_int,
      anon_sym_i64,
      anon_sym_u8,
      anon_sym_u16,
      anon_sym_u32,
      anon_sym_uint,
      anon_sym_u64,
      anon_sym_f32,
      anon_sym_f64,
      anon_sym_float,
      anon_sym_bool,
      anon_sym_string,
      anon_sym_ptr,
      anon_sym_anyptr,
      anon_sym_rawptr,
      anon_sym_self,
      anon_sym_null,
  [464] = 2,
    ACTIONS(91), 1,
      anon_sym_any,
    ACTIONS(89), 24,
      ts_builtin_sym_end,
      anon_sym_var,
      anon_sym_const,
      anon_sym_type,
      anon_sym_i8,
      anon_sym_i16,
      anon_sym_i32,
      anon_sym_int,
      anon_sym_i64,
      anon_sym_u8,
      anon_sym_u16,
      anon_sym_u32,
      anon_sym_uint,
      anon_sym_u64,
      anon_sym_f32,
      anon_sym_f64,
      anon_sym_float,
      anon_sym_bool,
      anon_sym_string,
      anon_sym_ptr,
      anon_sym_anyptr,
      anon_sym_rawptr,
      anon_sym_self,
      anon_sym_null,
  [494] = 2,
    ACTIONS(95), 1,
      anon_sym_any,
    ACTIONS(93), 24,
      ts_builtin_sym_end,
      anon_sym_var,
      anon_sym_const,
      anon_sym_type,
      anon_sym_i8,
      anon_sym_i16,
      anon_sym_i32,
      anon_sym_int,
      anon_sym_i64,
      anon_sym_u8,
      anon_sym_u16,
      anon_sym_u32,
      anon_sym_uint,
      anon_sym_u64,
      anon_sym_f32,
      anon_sym_f64,
      anon_sym_float,
      anon_sym_bool,
      anon_sym_string,
      anon_sym_ptr,
      anon_sym_anyptr,
      anon_sym_rawptr,
      anon_sym_self,
      anon_sym_null,
  [524] = 2,
    ACTIONS(99), 1,
      anon_sym_any,
    ACTIONS(97), 24,
      ts_builtin_sym_end,
      anon_sym_var,
      anon_sym_const,
      anon_sym_type,
      anon_sym_i8,
      anon_sym_i16,
      anon_sym_i32,
      anon_sym_int,
      anon_sym_i64,
      anon_sym_u8,
      anon_sym_u16,
      anon_sym_u32,
      anon_sym_uint,
      anon_sym_u64,
      anon_sym_f32,
      anon_sym_f64,
      anon_sym_float,
      anon_sym_bool,
      anon_sym_string,
      anon_sym_ptr,
      anon_sym_anyptr,
      anon_sym_rawptr,
      anon_sym_self,
      anon_sym_null,
  [554] = 2,
    ACTIONS(103), 1,
      anon_sym_any,
    ACTIONS(101), 24,
      ts_builtin_sym_end,
      anon_sym_var,
      anon_sym_const,
      anon_sym_type,
      anon_sym_i8,
      anon_sym_i16,
      anon_sym_i32,
      anon_sym_int,
      anon_sym_i64,
      anon_sym_u8,
      anon_sym_u16,
      anon_sym_u32,
      anon_sym_uint,
      anon_sym_u64,
      anon_sym_f32,
      anon_sym_f64,
      anon_sym_float,
      anon_sym_bool,
      anon_sym_string,
      anon_sym_ptr,
      anon_sym_anyptr,
      anon_sym_rawptr,
      anon_sym_self,
      anon_sym_null,
  [584] = 2,
    ACTIONS(107), 1,
      anon_sym_any,
    ACTIONS(105), 24,
      ts_builtin_sym_end,
      anon_sym_var,
      anon_sym_const,
      anon_sym_type,
      anon_sym_i8,
      anon_sym_i16,
      anon_sym_i32,
      anon_sym_int,
      anon_sym_i64,
      anon_sym_u8,
      anon_sym_u16,
      anon_sym_u32,
      anon_sym_uint,
      anon_sym_u64,
      anon_sym_f32,
      anon_sym_f64,
      anon_sym_float,
      anon_sym_bool,
      anon_sym_string,
      anon_sym_ptr,
      anon_sym_anyptr,
      anon_sym_rawptr,
      anon_sym_self,
      anon_sym_null,
  [614] = 2,
    ACTIONS(50), 1,
      anon_sym_any,
    ACTIONS(48), 24,
      ts_builtin_sym_end,
      anon_sym_var,
      anon_sym_const,
      anon_sym_type,
      anon_sym_i8,
      anon_sym_i16,
      anon_sym_i32,
      anon_sym_int,
      anon_sym_i64,
      anon_sym_u8,
      anon_sym_u16,
      anon_sym_u32,
      anon_sym_uint,
      anon_sym_u64,
      anon_sym_f32,
      anon_sym_f64,
      anon_sym_float,
      anon_sym_bool,
      anon_sym_string,
      anon_sym_ptr,
      anon_sym_anyptr,
      anon_sym_rawptr,
      anon_sym_self,
      anon_sym_null,
  [644] = 5,
    ACTIONS(36), 1,
      anon_sym_any,
    STATE(5), 1,
      sym__null,
    STATE(6), 1,
      sym_baseType,
    STATE(11), 2,
      sym_singleType,
      sym_optionType,
    ACTIONS(34), 20,
      anon_sym_i8,
      anon_sym_i16,
      anon_sym_i32,
      anon_sym_int,
      anon_sym_i64,
      anon_sym_u8,
      anon_sym_u16,
      anon_sym_u32,
      anon_sym_uint,
      anon_sym_u64,
      anon_sym_f32,
      anon_sym_f64,
      anon_sym_float,
      anon_sym_bool,
      anon_sym_string,
      anon_sym_ptr,
      anon_sym_anyptr,
      anon_sym_rawptr,
      anon_sym_self,
      anon_sym_null,
  [680] = 12,
    ACTIONS(111), 1,
      sym_intLiteral,
    ACTIONS(115), 1,
      anon_sym_DQUOTE,
    ACTIONS(117), 1,
      anon_sym_BQUOTE,
    ACTIONS(119), 1,
      anon_sym_SQUOTE,
    ACTIONS(121), 1,
      anon_sym_LBRACK,
    ACTIONS(123), 1,
      anon_sym_RBRACK,
    STATE(26), 1,
      aux_sym_arrayLiteral_repeat1,
    STATE(32), 1,
      sym_expression,
    STATE(36), 1,
      sym_floatLiteral,
    ACTIONS(109), 3,
      sym_boolLiteral,
      sym_identifier,
      anon_sym_null,
    ACTIONS(113), 3,
      aux_sym_floatLiteral_token1,
      aux_sym_floatLiteral_token2,
      aux_sym_floatLiteral_token3,
    STATE(34), 5,
      sym_numberLiteral,
      sym_stringLiteral,
      sym_charLiteral,
      sym_arrayLiteral,
      sym__null,
  [725] = 12,
    ACTIONS(128), 1,
      sym_intLiteral,
    ACTIONS(134), 1,
      anon_sym_DQUOTE,
    ACTIONS(137), 1,
      anon_sym_BQUOTE,
    ACTIONS(140), 1,
      anon_sym_SQUOTE,
    ACTIONS(143), 1,
      anon_sym_LBRACK,
    ACTIONS(146), 1,
      anon_sym_RBRACK,
    STATE(26), 1,
      aux_sym_arrayLiteral_repeat1,
    STATE(32), 1,
      sym_expression,
    STATE(36), 1,
      sym_floatLiteral,
    ACTIONS(125), 3,
      sym_boolLiteral,
      sym_identifier,
      anon_sym_null,
    ACTIONS(131), 3,
      aux_sym_floatLiteral_token1,
      aux_sym_floatLiteral_token2,
      aux_sym_floatLiteral_token3,
    STATE(34), 5,
      sym_numberLiteral,
      sym_stringLiteral,
      sym_charLiteral,
      sym_arrayLiteral,
      sym__null,
  [770] = 12,
    ACTIONS(111), 1,
      sym_intLiteral,
    ACTIONS(115), 1,
      anon_sym_DQUOTE,
    ACTIONS(117), 1,
      anon_sym_BQUOTE,
    ACTIONS(119), 1,
      anon_sym_SQUOTE,
    ACTIONS(121), 1,
      anon_sym_LBRACK,
    ACTIONS(148), 1,
      anon_sym_RBRACK,
    STATE(26), 1,
      aux_sym_arrayLiteral_repeat1,
    STATE(32), 1,
      sym_expression,
    STATE(36), 1,
      sym_floatLiteral,
    ACTIONS(109), 3,
      sym_boolLiteral,
      sym_identifier,
      anon_sym_null,
    ACTIONS(113), 3,
      aux_sym_floatLiteral_token1,
      aux_sym_floatLiteral_token2,
      aux_sym_floatLiteral_token3,
    STATE(34), 5,
      sym_numberLiteral,
      sym_stringLiteral,
      sym_charLiteral,
      sym_arrayLiteral,
      sym__null,
  [815] = 11,
    ACTIONS(111), 1,
      sym_intLiteral,
    ACTIONS(115), 1,
      anon_sym_DQUOTE,
    ACTIONS(117), 1,
      anon_sym_BQUOTE,
    ACTIONS(119), 1,
      anon_sym_SQUOTE,
    ACTIONS(121), 1,
      anon_sym_LBRACK,
    STATE(27), 1,
      aux_sym_arrayLiteral_repeat1,
    STATE(32), 1,
      sym_expression,
    STATE(36), 1,
      sym_floatLiteral,
    ACTIONS(109), 3,
      sym_boolLiteral,
      sym_identifier,
      anon_sym_null,
    ACTIONS(113), 3,
      aux_sym_floatLiteral_token1,
      aux_sym_floatLiteral_token2,
      aux_sym_floatLiteral_token3,
    STATE(34), 5,
      sym_numberLiteral,
      sym_stringLiteral,
      sym_charLiteral,
      sym_arrayLiteral,
      sym__null,
  [857] = 11,
    ACTIONS(111), 1,
      sym_intLiteral,
    ACTIONS(115), 1,
      anon_sym_DQUOTE,
    ACTIONS(117), 1,
      anon_sym_BQUOTE,
    ACTIONS(119), 1,
      anon_sym_SQUOTE,
    ACTIONS(121), 1,
      anon_sym_LBRACK,
    STATE(25), 1,
      aux_sym_arrayLiteral_repeat1,
    STATE(32), 1,
      sym_expression,
    STATE(36), 1,
      sym_floatLiteral,
    ACTIONS(109), 3,
      sym_boolLiteral,
      sym_identifier,
      anon_sym_null,
    ACTIONS(113), 3,
      aux_sym_floatLiteral_token1,
      aux_sym_floatLiteral_token2,
      aux_sym_floatLiteral_token3,
    STATE(34), 5,
      sym_numberLiteral,
      sym_stringLiteral,
      sym_charLiteral,
      sym_arrayLiteral,
      sym__null,
  [899] = 10,
    ACTIONS(152), 1,
      sym_intLiteral,
    ACTIONS(156), 1,
      anon_sym_DQUOTE,
    ACTIONS(158), 1,
      anon_sym_BQUOTE,
    ACTIONS(160), 1,
      anon_sym_SQUOTE,
    ACTIONS(162), 1,
      anon_sym_LBRACK,
    STATE(15), 1,
      sym_floatLiteral,
    STATE(16), 1,
      sym_expression,
    ACTIONS(150), 3,
      sym_boolLiteral,
      sym_identifier,
      anon_sym_null,
    ACTIONS(154), 3,
      aux_sym_floatLiteral_token1,
      aux_sym_floatLiteral_token2,
      aux_sym_floatLiteral_token3,
    STATE(17), 5,
      sym_numberLiteral,
      sym_stringLiteral,
      sym_charLiteral,
      sym_arrayLiteral,
      sym__null,
  [938] = 10,
    ACTIONS(152), 1,
      sym_intLiteral,
    ACTIONS(156), 1,
      anon_sym_DQUOTE,
    ACTIONS(158), 1,
      anon_sym_BQUOTE,
    ACTIONS(160), 1,
      anon_sym_SQUOTE,
    ACTIONS(162), 1,
      anon_sym_LBRACK,
    STATE(15), 1,
      sym_floatLiteral,
    STATE(18), 1,
      sym_expression,
    ACTIONS(150), 3,
      sym_boolLiteral,
      sym_identifier,
      anon_sym_null,
    ACTIONS(154), 3,
      aux_sym_floatLiteral_token1,
      aux_sym_floatLiteral_token2,
      aux_sym_floatLiteral_token3,
    STATE(17), 5,
      sym_numberLiteral,
      sym_stringLiteral,
      sym_charLiteral,
      sym_arrayLiteral,
      sym__null,
  [977] = 3,
    ACTIONS(168), 1,
      anon_sym_COMMA,
    ACTIONS(164), 4,
      sym_intLiteral,
      sym_boolLiteral,
      sym_identifier,
      anon_sym_null,
    ACTIONS(166), 8,
      aux_sym_floatLiteral_token1,
      aux_sym_floatLiteral_token2,
      aux_sym_floatLiteral_token3,
      anon_sym_DQUOTE,
      anon_sym_BQUOTE,
      anon_sym_SQUOTE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [997] = 2,
    ACTIONS(107), 4,
      sym_intLiteral,
      sym_boolLiteral,
      sym_identifier,
      anon_sym_null,
    ACTIONS(105), 9,
      aux_sym_floatLiteral_token1,
      aux_sym_floatLiteral_token2,
      aux_sym_floatLiteral_token3,
      anon_sym_DQUOTE,
      anon_sym_BQUOTE,
      anon_sym_SQUOTE,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [1015] = 2,
    ACTIONS(87), 4,
      sym_intLiteral,
      sym_boolLiteral,
      sym_identifier,
      anon_sym_null,
    ACTIONS(85), 9,
      aux_sym_floatLiteral_token1,
      aux_sym_floatLiteral_token2,
      aux_sym_floatLiteral_token3,
      anon_sym_DQUOTE,
      anon_sym_BQUOTE,
      anon_sym_SQUOTE,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [1033] = 2,
    ACTIONS(75), 4,
      sym_intLiteral,
      sym_boolLiteral,
      sym_identifier,
      anon_sym_null,
    ACTIONS(73), 9,
      aux_sym_floatLiteral_token1,
      aux_sym_floatLiteral_token2,
      aux_sym_floatLiteral_token3,
      anon_sym_DQUOTE,
      anon_sym_BQUOTE,
      anon_sym_SQUOTE,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [1051] = 2,
    ACTIONS(79), 4,
      sym_intLiteral,
      sym_boolLiteral,
      sym_identifier,
      anon_sym_null,
    ACTIONS(77), 9,
      aux_sym_floatLiteral_token1,
      aux_sym_floatLiteral_token2,
      aux_sym_floatLiteral_token3,
      anon_sym_DQUOTE,
      anon_sym_BQUOTE,
      anon_sym_SQUOTE,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [1069] = 2,
    ACTIONS(103), 4,
      sym_intLiteral,
      sym_boolLiteral,
      sym_identifier,
      anon_sym_null,
    ACTIONS(101), 9,
      aux_sym_floatLiteral_token1,
      aux_sym_floatLiteral_token2,
      aux_sym_floatLiteral_token3,
      anon_sym_DQUOTE,
      anon_sym_BQUOTE,
      anon_sym_SQUOTE,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [1087] = 2,
    ACTIONS(99), 4,
      sym_intLiteral,
      sym_boolLiteral,
      sym_identifier,
      anon_sym_null,
    ACTIONS(97), 9,
      aux_sym_floatLiteral_token1,
      aux_sym_floatLiteral_token2,
      aux_sym_floatLiteral_token3,
      anon_sym_DQUOTE,
      anon_sym_BQUOTE,
      anon_sym_SQUOTE,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [1105] = 2,
    ACTIONS(170), 4,
      sym_intLiteral,
      sym_boolLiteral,
      sym_identifier,
      anon_sym_null,
    ACTIONS(146), 8,
      aux_sym_floatLiteral_token1,
      aux_sym_floatLiteral_token2,
      aux_sym_floatLiteral_token3,
      anon_sym_DQUOTE,
      anon_sym_BQUOTE,
      anon_sym_SQUOTE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [1122] = 2,
    ACTIONS(172), 1,
      anon_sym_QMARK,
    ACTIONS(42), 2,
      anon_sym_PIPE,
      sym_identifier,
  [1130] = 3,
    ACTIONS(54), 1,
      sym_identifier,
    ACTIONS(174), 1,
      anon_sym_PIPE,
    STATE(43), 1,
      aux_sym_unionType_repeat1,
  [1140] = 3,
    ACTIONS(48), 1,
      sym_identifier,
    ACTIONS(174), 1,
      anon_sym_PIPE,
    STATE(41), 1,
      aux_sym_unionType_repeat1,
  [1150] = 3,
    ACTIONS(58), 1,
      sym_identifier,
    ACTIONS(176), 1,
      anon_sym_PIPE,
    STATE(43), 1,
      aux_sym_unionType_repeat1,
  [1160] = 1,
    ACTIONS(38), 3,
      anon_sym_QMARK,
      anon_sym_PIPE,
      sym_identifier,
  [1166] = 1,
    ACTIONS(58), 2,
      anon_sym_PIPE,
      sym_identifier,
  [1171] = 1,
    ACTIONS(65), 2,
      anon_sym_PIPE,
      sym_identifier,
  [1176] = 1,
    ACTIONS(179), 1,
      anon_sym_SQUOTE,
  [1180] = 1,
    ACTIONS(181), 1,
      anon_sym_DQUOTE,
  [1184] = 1,
    ACTIONS(183), 1,
      anon_sym_EQ,
  [1188] = 1,
    ACTIONS(48), 1,
      sym_identifier,
  [1192] = 1,
    ACTIONS(185), 1,
      sym_identifier,
  [1196] = 1,
    ACTIONS(187), 1,
      anon_sym_EQ,
  [1200] = 1,
    ACTIONS(189), 1,
      aux_sym_stringLiteral_token1,
  [1204] = 1,
    ACTIONS(191), 1,
      aux_sym_charLiteral_token1,
  [1208] = 1,
    ACTIONS(193), 1,
      ts_builtin_sym_end,
  [1212] = 1,
    ACTIONS(195), 1,
      sym_identifier,
  [1216] = 1,
    ACTIONS(181), 1,
      anon_sym_BQUOTE,
  [1220] = 1,
    ACTIONS(197), 1,
      anon_sym_SQUOTE,
  [1224] = 1,
    ACTIONS(199), 1,
      anon_sym_DQUOTE,
  [1228] = 1,
    ACTIONS(199), 1,
      anon_sym_BQUOTE,
  [1232] = 1,
    ACTIONS(201), 1,
      anon_sym_EQ,
  [1236] = 1,
    ACTIONS(203), 1,
      aux_sym_stringLiteral_token1,
  [1240] = 1,
    ACTIONS(205), 1,
      aux_sym_stringLiteral_token1,
  [1244] = 1,
    ACTIONS(207), 1,
      aux_sym_stringLiteral_token1,
  [1248] = 1,
    ACTIONS(209), 1,
      aux_sym_charLiteral_token1,
  [1252] = 1,
    ACTIONS(211), 1,
      sym_identifier,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(4)] = 0,
  [SMALL_STATE(5)] = 42,
  [SMALL_STATE(6)] = 74,
  [SMALL_STATE(7)] = 108,
  [SMALL_STATE(8)] = 144,
  [SMALL_STATE(9)] = 180,
  [SMALL_STATE(10)] = 216,
  [SMALL_STATE(11)] = 247,
  [SMALL_STATE(12)] = 278,
  [SMALL_STATE(13)] = 308,
  [SMALL_STATE(14)] = 338,
  [SMALL_STATE(15)] = 374,
  [SMALL_STATE(16)] = 404,
  [SMALL_STATE(17)] = 434,
  [SMALL_STATE(18)] = 464,
  [SMALL_STATE(19)] = 494,
  [SMALL_STATE(20)] = 524,
  [SMALL_STATE(21)] = 554,
  [SMALL_STATE(22)] = 584,
  [SMALL_STATE(23)] = 614,
  [SMALL_STATE(24)] = 644,
  [SMALL_STATE(25)] = 680,
  [SMALL_STATE(26)] = 725,
  [SMALL_STATE(27)] = 770,
  [SMALL_STATE(28)] = 815,
  [SMALL_STATE(29)] = 857,
  [SMALL_STATE(30)] = 899,
  [SMALL_STATE(31)] = 938,
  [SMALL_STATE(32)] = 977,
  [SMALL_STATE(33)] = 997,
  [SMALL_STATE(34)] = 1015,
  [SMALL_STATE(35)] = 1033,
  [SMALL_STATE(36)] = 1051,
  [SMALL_STATE(37)] = 1069,
  [SMALL_STATE(38)] = 1087,
  [SMALL_STATE(39)] = 1105,
  [SMALL_STATE(40)] = 1122,
  [SMALL_STATE(41)] = 1130,
  [SMALL_STATE(42)] = 1140,
  [SMALL_STATE(43)] = 1150,
  [SMALL_STATE(44)] = 1160,
  [SMALL_STATE(45)] = 1166,
  [SMALL_STATE(46)] = 1171,
  [SMALL_STATE(47)] = 1176,
  [SMALL_STATE(48)] = 1180,
  [SMALL_STATE(49)] = 1184,
  [SMALL_STATE(50)] = 1188,
  [SMALL_STATE(51)] = 1192,
  [SMALL_STATE(52)] = 1196,
  [SMALL_STATE(53)] = 1200,
  [SMALL_STATE(54)] = 1204,
  [SMALL_STATE(55)] = 1208,
  [SMALL_STATE(56)] = 1212,
  [SMALL_STATE(57)] = 1216,
  [SMALL_STATE(58)] = 1220,
  [SMALL_STATE(59)] = 1224,
  [SMALL_STATE(60)] = 1228,
  [SMALL_STATE(61)] = 1232,
  [SMALL_STATE(62)] = 1236,
  [SMALL_STATE(63)] = 1240,
  [SMALL_STATE(64)] = 1244,
  [SMALL_STATE(65)] = 1248,
  [SMALL_STATE(66)] = 1252,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(44),
  [15] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [19] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(56),
  [22] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(51),
  [25] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(66),
  [28] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(44),
  [31] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(44),
  [34] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [36] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [38] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_baseType, 1, 0, 0),
  [40] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_baseType, 1, 0, 0),
  [42] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_singleType, 1, 0, 0),
  [44] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_singleType, 1, 0, 0),
  [46] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [48] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type, 1, 0, 0),
  [50] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_type, 1, 0, 0),
  [52] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [54] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unionType, 2, 0, 0),
  [56] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unionType, 2, 0, 0),
  [58] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_unionType_repeat1, 2, 0, 0),
  [60] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_unionType_repeat1, 2, 0, 0),
  [62] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_unionType_repeat1, 2, 0, 0), SHIFT_REPEAT(24),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_optionType, 2, 0, 0),
  [67] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_optionType, 2, 0, 0),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statements, 1, 0, 0),
  [71] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_statements, 1, 0, 0),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_floatLiteral, 1, 0, 0),
  [75] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_floatLiteral, 1, 0, 0),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_numberLiteral, 1, 0, 0),
  [79] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_numberLiteral, 1, 0, 0),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_varDecl, 4, 0, 1),
  [83] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_varDecl, 4, 0, 1),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 1, 0, 0),
  [87] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression, 1, 0, 0),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_constDecl, 4, 0, 1),
  [91] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_constDecl, 4, 0, 1),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_typeDecl, 4, 0, 2),
  [95] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_typeDecl, 4, 0, 2),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arrayLiteral, 3, 0, 0),
  [99] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_arrayLiteral, 3, 0, 0),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_stringLiteral, 3, 0, 0),
  [103] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_stringLiteral, 3, 0, 0),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_charLiteral, 3, 0, 0),
  [107] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_charLiteral, 3, 0, 0),
  [109] = {.entry = {.count = 1, .reusable = false}}, SHIFT(34),
  [111] = {.entry = {.count = 1, .reusable = false}}, SHIFT(36),
  [113] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [115] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [117] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [119] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [121] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [123] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [125] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_arrayLiteral_repeat1, 2, 0, 0), SHIFT_REPEAT(34),
  [128] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_arrayLiteral_repeat1, 2, 0, 0), SHIFT_REPEAT(36),
  [131] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_arrayLiteral_repeat1, 2, 0, 0), SHIFT_REPEAT(35),
  [134] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_arrayLiteral_repeat1, 2, 0, 0), SHIFT_REPEAT(63),
  [137] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_arrayLiteral_repeat1, 2, 0, 0), SHIFT_REPEAT(64),
  [140] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_arrayLiteral_repeat1, 2, 0, 0), SHIFT_REPEAT(65),
  [143] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_arrayLiteral_repeat1, 2, 0, 0), SHIFT_REPEAT(28),
  [146] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_arrayLiteral_repeat1, 2, 0, 0),
  [148] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [150] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [152] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [154] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [156] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [158] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [160] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [162] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [164] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_arrayLiteral_repeat1, 1, 0, 0),
  [166] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_arrayLiteral_repeat1, 1, 0, 0),
  [168] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [170] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_arrayLiteral_repeat1, 2, 0, 0),
  [172] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [174] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [176] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_unionType_repeat1, 2, 0, 0), SHIFT_REPEAT(14),
  [179] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [181] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [183] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [185] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [187] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [189] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [191] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [193] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [195] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [197] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [199] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [201] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [203] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [205] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [207] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [209] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [211] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_nature(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
    .name = "nature",
    .reserved_words = &ts_reserved_words[0][0],
    .max_reserved_word_set_size = 3,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
